name: 'Upload app settings'
description: 'Upload the application settings from github secrets to azure web app'
inputs:
  upload_app_settings:  # id of input
    description: 'JSON string with '
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'index.js'