on: [push]

jobs:
  update_app_settings_job:
    runs-on: ubuntu-latest
    name: Upload the application settings from github secrets to azure web app
    steps:
      # To use this repository's private action, you must check out the repository
      - uses: actions/checkout@v1
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Upload app settings
        uses: ./ # Uses an action in the root directory
        id: upload_app_settings
        with:
          app_secrets: ${{ secrets.APP_SECRETS }}