name: PR Build

on: 
  pull_request


jobs:
  build:

    runs-on: ubuntu-latest

    env:
      node-version: 12.x

    steps:
    - name: generate jetzt config
      run: |
        fetch_pull_request_id="jq '.pull_request.id' $GITHUB_EVENT_PATH"
        pull_request_id=$(eval "$fetch_pull_request_id")
        echo "$pull_request_id"
        name=$(echo "${{ secrets.AZ_FUNC_NAME }}-$pull_request_id}" | sed "s/[^a-zA-Z0-9\-]/-/g")
        echo "$name"