name: PR Build

on: 
  pull_request


jobs:
  build:

    runs-on: ubuntu-latest

    env:
      node-version: 12.x

    steps:
    - name: generate jetzt config
      run: |
        echo $GITHUB_EVENT_PATH
        value=$(<$GITHUB_EVENT_PATH)
        jq '.pull_request.id' $GITHUB_EVENT_PATH