name: PR Build

on: 
  pull_request


jobs:
  build:

    runs-on: ubuntu-latest

    env:
      node-version: 12.x

    steps:
    - name: set env
      run: |
        name=$(echo "${{ secrets.AZ_FUNC_NAME }}-$(eval "jq '.pull_request.id' $GITHUB_EVENT_PATH")}" | sed "s/[^a-zA-Z0-9\-]/-/g")
        echo "Function name: $name"
        echo "::set-env name=action_state::yellow"
    - name: use env
      run: |
        echo "${{ env.action_state }}"